#!/usr/bin/env python3
"""Regenerate the Snowflake scroll-line (ticker) in index.html.

Reads the Snowflake Bay Area user group feed
(https://usergroups.snowflake.com/bay-area/), parses the embedded __NEXT_DATA__
JSON, and rewrites the block between the TICKER:START / TICKER:END markers in
index.html: an evergreen intro, the next upcoming meetup, and the last one.

Usage:
    python3 render_ticker.py            # fetch the live feed
    python3 render_ticker.py page.html  # parse a saved copy (offline / testing)
"""
import html
import json
import re
import sys
import urllib.request
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

FEED_URL = "https://usergroups.snowflake.com/bay-area/"
PACIFIC = ZoneInfo("America/Los_Angeles")
REPO_ROOT = Path(__file__).resolve().parents[3]
INDEX = REPO_ROOT / "index.html"
INDENT = "        "
SEP = '<span class="ticker-sep">❄</span>'
INTRO = (
    '<a class="ticker-story" href="https://usergroups.snowflake.com/bay-area/">'
    "🏔️ <strong>Now leading the Snowflake Bay Area Users Group</strong> — "
    "bringing the community together around Snowflake, data engineering, and AI. "
    '&nbsp;·&nbsp; <span class="cta">Click here →</span></a>'
)


def load_html(arg):
    if arg:
        return Path(arg).read_text(encoding="utf-8")
    req = urllib.request.Request(FEED_URL, headers={"User-Agent": "Mozilla/5.0 (update-ticker skill)"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def clean(title):
    return title.split(" | ")[0].split(" @ ")[0].strip()


def fmt(dt):
    return dt.astimezone(PACIFIC).strftime("%B %-d, %Y")


def parse_events(page):
    m = re.search(r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>', page, re.S)
    if not m:
        sys.exit("error: __NEXT_DATA__ not found — the feed's page structure changed.")
    pd = json.loads(m.group(1))["props"]["pageProps"]["prerenderData"]

    def rows(bucket):
        out = []
        for e in pd.get(bucket, {}).get("results", []):
            out.append({
                "title": clean(e.get("title", "")),
                "url": e.get("url") or FEED_URL,
                "dt": datetime.fromisoformat(e["start_date"].replace("Z", "+00:00")),
            })
        return out

    upcoming = sorted(rows("upcomingEvents"), key=lambda e: e["dt"])
    past = sorted(rows("pastEvents"), key=lambda e: e["dt"], reverse=True)
    return upcoming, past


def stanza(emoji, label, ev, cta):
    return (
        f'<a class="ticker-story" href="{html.escape(ev["url"], quote=True)}">'
        f'{emoji} <strong>{label}: {html.escape(ev["title"])} — {fmt(ev["dt"])}</strong> '
        f'&nbsp;·&nbsp; <span class="cta">{cta} →</span></a>'
    )


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else None
    upcoming, past = parse_events(load_html(arg))

    parts = [INTRO]
    if upcoming:
        parts.append(stanza("🛠️", "Next up", upcoming[0], "Details"))
    if past:
        parts.append(stanza("✅", "Last meetup", past[0], "Recap"))

    lines = []
    for i, part in enumerate(parts):
        if i:
            lines.append(SEP)
        lines.append(part)
    body = "".join(f"\n{INDENT}{ln}" for ln in lines)
    block = (
        "<!-- TICKER:START — generated by the update-ticker skill; do not edit by hand -->"
        f"{body}\n{INDENT}<!-- TICKER:END -->"
    )

    text = INDEX.read_text(encoding="utf-8")
    if "TICKER:START" not in text or "TICKER:END" not in text:
        sys.exit(f"error: TICKER markers not found in {INDEX}. Add them around the .ticker-inner content.")
    new = re.sub(r"<!-- TICKER:START.*?TICKER:END -->", lambda _m: block, text, count=1, flags=re.S)

    changed = new != text
    if changed:
        INDEX.write_text(new, encoding="utf-8")

    print("Ticker regenerated." if changed else "Ticker already up to date — no change written.")
    if upcoming:
        nxt = upcoming[0]
        print(f"  Next up:     {nxt['title']} — {fmt(nxt['dt'])}")
        remind = (nxt["dt"].astimezone(PACIFIC) + timedelta(days=1)).strftime("%Y-%m-%d")
        print(f"  REMIND_ON={remind}  (schedule /update-ticker for the morning after this event)")
    else:
        print("  Next up:     (none listed on the feed)")
        print("  REMIND_ON=  (no upcoming event — check the feed again later)")
    if past:
        last = past[0]
        print(f"  Last meetup: {last['title']} — {fmt(last['dt'])}")


if __name__ == "__main__":
    main()
